# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DETAILS', '0003_auto_20180606_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmarks',
            old_name='subject',
            new_name='subjectname',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DETAILS.StudentMarks'),
        ),
    ]
