# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DETAILS', '0004_auto_20180606_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmarks',
            old_name='subjectname',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_subjects', to='DETAILS.StudentMarks'),
        ),
    ]
