# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.CharField(max_length=50, null=True)),
                ('director', models.CharField(max_length=50, null=True)),
                ('genre', models.CharField(max_length=50, null=True)),
                ('movielist_score', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('dt_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
