# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VIKAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectfaculty',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='VIKAS.StudentMarks'),
        ),
    ]
